#!/usr/bin/python
# -*- coding: UTF-8 -*-

fq_account_qv = 'account'
fq_data_qv = 'data'
fq_f_object_qv = 'f_object'
fq_grupa_qv = 'grupa'
fq_imie_qv = 'imie'
fq_k_object_qv = 'k_object'
fq_k_power_qv = 'k_power'
fq_k_sample_qv = 'k_sample'
fq_m_date_qv = 'm_date'
fq_m_none_qv = 'm_none'
fq_moc_qv = 'moc'
fq_m_samples_qv = 'm_samples'
fq_m_sum_qv = 'm_sum'
fq_m_zero_qv = 'm_zero'
fq_nazwa_qv = 'nazwa'
fq_nazwisko_qv = 'nazwisko'
fq_rodzaj_qv = 'rodzaj'
fq_tekst_qv = 'tekst'
fq_uu_energy_qv = 'uu_energy'
fq_uu_object_qv = 'uu_object'
fq_uu_power_qv = 'uu_power'
